Spider
akruglov18/Game pull request #75
Opened 2022-04-09 21:52 UTC by vladikganja

Добавил класс паука с начальными анимациями, пофиксил баг, когда существа на одной клетке не отображались.

2022-04-10 20:49 UTC, akruglov18 commented
посмотрю, как первый вмержу, изменений много, сложно отследить что изменилось

2022-04-12 05:38 UTC, akruglov18 commented
надо поребейзить

2022-04-14 12:30 UTC, akruglov18 requested changes

2022-04-14 12:30 UTC, akruglov18 commented on animation/animation.cpp
> +
Думаю, что стоит добавить описание.
За какую анимацию отвечает каждый элемент вектора.

2022-04-14 12:30 UTC, akruglov18 commented on animation/animation.cpp
>      }
пропущен `break`

2022-04-14 12:30 UTC, akruglov18 commented on animation/animation.cpp
> +    }
Этот код используется часто, можно сделать отдельную функцию.

2022-04-14 12:30 UTC, akruglov18 commented on game/game.cpp
> +        //enemies[i]->set_armor(Pants::make_pants(PantsType::Pants_plate));
думаю, что выдачу брони можно перенести в функцию спавна врагов

2022-04-14 12:30 UTC, akruglov18 commented on creature/enemy.cpp
>  }
Что именно делает этот код?
выглядит очень странно

2022-04-14 21:07 UTC, vladikganja commented on action/action.cpp
>          return;
Не вижу смысла, здесь просто выполняется change_mode и выбирается duration, если кончилось время удара. Такая реализация кажется мне вполне логичной

2022-04-14 21:08 UTC, vladikganja commented on animation/animation.cpp
> +
там на 3 строке комментарий есть

2022-04-14 21:17 UTC, vladikganja commented on game/game.cpp
> +        //enemies[i]->set_armor(Pants::make_pants(PantsType::Pants_plate));
Да, броня должна выдаваться почти случайным образом, в зависимости от сложности, уровня, локации и т.д.
Но этим нужно заняться позже. В отдельном пулл реквесте, с отдельной таской

2022-04-14 21:19 UTC, vladikganja commented on creature/enemy.cpp
>  }
Пока это просто болванка кода, ничего функционального. Просто время от времени я меняю местами строки с hit, move и stay, чтобы проверять поведение существ. В дальнейшем здесь будет вызываться логика ИИ

2022-04-15 07:21 UTC, akruglov18 commented
Не вижу изменений

2022-04-15 07:36 UTC, akruglov18 submitted a review, later dismissed

2022-04-15 07:42 UTC, akruglov18 approved these changes

2022-04-15 07:46 UTC, merged