Hitbox
akruglov18/Game pull request #77
Opened 2022-04-12 23:54 UTC by vladikganja

Добавил hitbox, collisionbox. У разных типов существ они свои, это задаётся в конструкторе для родителя автоматически.
Реализовал механику столкновений объектов.
Чтобы увидеть боксы во время игры, нужно нажать клавишу B

2022-04-15 15:08 UTC, akruglov18 requested changes

2022-04-15 15:08 UTC, akruglov18 commented on animation/animation.cpp
Удалить пустую строку

2022-04-15 15:08 UTC, akruglov18 commented on utils/utils.cpp
> +}
Если это просто перебор всех пар, то я думаю, что лучше сделать 
`for(i =0, i < size; i++)`
    `for(j = i + 1, j < size; j++)`
  Чтобы не проверять одни и те же пары 2 раза

2022-04-15 15:08 UTC, akruglov18 commented on utils/utils.cpp
> +    return false;
Насколько я помню класс sf::Rect уже предоставляет возможность проверки пересечения прямоугольников
Почему не воспользоваться им?

2022-04-15 15:40 UTC, vladikganja commented on utils/utils.cpp
> +}
увы, тут так не выйдет, потому что проверка на can_move делается для i-того существа, при том j-тое может быть как движимо, так и нет. Если они столкнулись лбами, то оба стопятся, если же один вдарил в бок другому, то второй может двигаться, а первый нет. Попробую сделать проверку направлений, тогда действительно можно ускорить

2022-04-15 15:41 UTC, vladikganja commented on utils/utils.cpp
> +    return false;
на 67 строке он и используется. Остальные проверки тоже нужны, чтобы всё нормально работало

2022-04-15 15:57 UTC, akruglov18 commented on utils/utils.cpp
> +    return false;
Да, просмотрел.
А почему по два ифа на каждый случай, их же можно в один объеденить?

2022-04-15 19:23 UTC, vladikganja commented on utils/utils.cpp
> +    return false;
сейчас поправлю

2022-04-15 20:51 UTC, akruglov18 commented on utils/utils.cpp
> +}
Предлагаю пока так оставить, это в целом как-то сомнительно выглядит, потом посмотрим как улучшить можно

2022-04-15 20:56 UTC, vladikganja commented on utils/utils.cpp
> +}
я уже придумал как ускорить это на 90%, сейчас попробую дожать до 95%

2022-04-15 21:58 UTC, akruglov18 commented on utils/utils.cpp
> +        }
если блок if со скобками, то и else с ними должен быть

2022-04-16 06:18 UTC, akruglov18 approved these changes

2022-04-16 06:18 UTC, merged