Add inventory
akruglov18/Game pull request #91
Opened 2022-04-27 23:16 UTC by vladikganja

2022-04-28 21:21 UTC, akruglov18 commented on equipment/items/coins.h
>      void chooseTexture();
почему удалил поле?

2022-04-28 21:21 UTC, akruglov18 commented on equipment/items/items.h
> +
за что отвечает это поле?

2022-04-29 09:43 UTC, vladikganja commented on equipment/items/coins.h
>      void chooseTexture();
перенес в базовый класс Items

2022-04-29 13:07 UTC, akruglov18 requested changes

2022-04-29 13:09 UTC, vladikganja commented on inventory/inventory.cpp
> +        value = 0;
согласен

2022-04-29 18:36 UTC, akruglov18 approved these changes

2022-04-29 18:36 UTC, merged